name: Node.js CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Copy files to Lightsail instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_IP }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: "dist"  # Change this to the directory where your build artifacts are located
        target: "/home/bitnami/OBGCFrontend"  # Change this to the destination directory on your Lightsail instance

    - name: SSH into Lightsail instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_IP }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /home/bitnami/OBGCFrontend
          npm install
          pm2 restart all
